// Defines the FastQC process
process QC_READS_FASTQC {
    tag "$sampleId (${stage})"
    
    label 'qcReadsFastQC'
    container "${params.container__kallisto}"

    // Fixed pattern to match the actual files generated by FastQC
    publishDir "${params.outputDir}/fastqc/${stage}", mode: 'copy', pattern: "*_fastqc.*"

    input:
    tuple val(sampleId), path(read1), path(read2)
    val stage // "raw" or "trimmed"

    output:
    // Fixed patterns to match standard FastQC outputs (e.g., sample_r1_fastqc.html)
    tuple val(sampleId), path("*_fastqc.zip"), path("*_fastqc.html"), emit: fastqc_files

    script:
    """
    # fastqc accepts R1 and R2 files separated by a space
    fastqc ${read1} ${read2}
    """
}